### ISSUE TITLE
Build Time Optimization - If possible 

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-dockerize-nextjs#1]
The set up runs successfully. The build took ~5min. 
If possible to reduce the build time, would be great.

**Comment by sgnd** [comment]
Hmm, I don't know why this happened. 
Because if I run on my local max only a 2-minute build (if don't have the node image).

**Comment by app-generator** [comment]
Is ok. please update the [Quick Start Section](https://github.com/app-generator/sample-dockerize-nextjs#-quick-start-in-docker) and this project is finished.
Ty!
